baseURL: 'https://www.pal-art.in/'
languageCode: 'en-us'
title: 'Parshottam Laxman Vadher | PAL Art'
theme: "ananke"
googleAnalytics: "G-QP990YRZ8P"
enableRobotsTXT: true
params:
  env: production
  # body_classes: avenir bg-near-white
  # site_logo:  
  ananke_socials:
  - name: facebook
    url: https://www.facebook.com/plvadher